### ISSUE TITLE
Notes are not saved in drive

### ISSUE THREAD

**Issue by audiovideovangils** [walty8/simple-gmail-notes.firefox#2]
Hi there,

First thank you for this great plugin!! We are very happy with it.

But for 2 days now (firefox update?) we have the problem that our notes are not saved any more to google drive.

Browser Version: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Last Summary Page URL: https://mail.google.com/mail/u/0/#label/Webmaster
Is Vertical Split: false
Is Horizontal Split: true
Is Preview Pane: false
Is Multiple Inbox: false
Is Conversation View: true
PE:[set up request sent][pull skipped][textarea already exists][message not found][no need to pull rows][pull request sent][no need to check]

documentReady, contentLoadStarted, contentLoadDone, startSetupNote

Extension Version: 0.7.3b

**Comment by walty8** [comment]
hi,

thanks for the reporting. pls see the following link for the details of this issue:

https://github.com/walty8/simple-gmail-notes.firefox/issues/1
